services:
  web:
    image: nginx:latest
    ports:
      - "1234:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: base
      args:
        PHP_ENVIRONMENT: development
        CRON: 0
    volumes:
      - .:/var/www/html
    links:
      - database
      - cache
      - mailhog
    environment:
      NEW_WKHTMLTOPDF: 1
      PHP_IDE_CONFIG: serverName=invoiced-docker

  queue-worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: base
      args:
        PHP_ENVIRONMENT: development
        CRON: 0
    volumes:
      - .:/var/www/html
    links:
      - database
      - cache
      - mailhog
    environment:
      NEW_WKHTMLTOPDF: 1
      PHP_IDE_CONFIG: serverName=invoiced-docker
    entrypoint: "php -d memory_limit=-1 /var/www/html/bin/console queue:work -vvv"

  scheduler-worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: base
      args:
        PHP_ENVIRONMENT: development
        CRON: 0
    volumes:
      - .:/var/www/html
    links:
      - database
      - cache
      - mailhog
    environment:
      PHP_IDE_CONFIG: serverName=invoiced-docker
    entrypoint: "php -d memory_limit=-1 /var/www/html/bin/console queue:work-delayed -vvv"

  cron-worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: base
      args:
        PHP_ENVIRONMENT: development
        CRON: 1
    volumes:
      - .:/var/www/html
    links:
      - database
      - cache
      - mailhog
    environment:
      NEW_WKHTMLTOPDF: 1
      PHP_IDE_CONFIG: serverName=invoiced-docker
    entrypoint: "cron -f -l 2"

  database:
    image: mariadb:10.6
    ports:
      - "3307:3306"
    volumes:
      - invoiced_db:/var/lib/mysql
      - ./docker/mariadb:/etc/mysql/conf.d
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: Invoiced

  cache:
    image: redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1235:8025"

  # Elasticsearch is not enabled by default because it is not generally
  # used in development. It can be installed with:
  #  docker-compose --profile=elasticsearch up -d
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - "9200:9200"
    volumes:
      - invoiced_elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    profiles: [ 'elasticsearch' ]

volumes:
  invoiced_db:
  invoiced_elasticsearch: