fields:
  address1: { name: "Address Line 1", type: string }
  address2: { name: "Address Line 2", type: string }
  city: { name: City, type: string }
  country: { name: Country, type: string }
  email: { name: Email, type: string }
  name: { name: Name, type: string }
  postal_code: { name: "Postal Code", type: string }
  state: { name: State, type: string }
  tax_id: { name: "Tax ID", type: string }
  type:
    name: Type
    type: enum
    values:
      company: Company
      government: Government
      non_profit: Non-Profit
      person: Individual
  username: { name: Username, type: string }