fields:
  company:
    name: Company
    type: join
    parent_column: tenant_id
    writable: false
    filterable: false
  created_at:
    name: Created At
    type: datetime
    date_format: "Y-m-d H:i:s"
    writable: false
  id:
    name: ID
    type: string
    writable: false
  invoice: { name: Invoice, type: join }
  status:
    name: Status
    type: enum
    values:
      pending_signup: Needs Approval
      active: Active
      finished: Finished
      canceled: Canceled
  updated_at:
    name: Updated At
    type: datetime
    date_format: "Y-m-d H:i:s"
    writable: false