fields:
  amount:
    name: Amount
    type: money
    summarize: true
    writable: false
  catalog_item: { name: "Item ID", type: string }
  created_at:
    name: Created At
    type: datetime
    date_format: "Y-m-d H:i:s"
    writable: false
  description: { name: Description, type: string }
  discountable: { name: Discountable, type: boolean }
  id:
    name: ID
    type: string
    writable: false
  name: { name: Name, type: string }
  period_end:
    name: "Period End"
    type: date
    writable: false
  period_start:
    name: "Period Start"
    type: date
    writable: false
  plan:
    name: Plan
    type: join
    join_column: internal_id
    writable: false
  prorated:
    name: Prorated
    type: boolean
    writable: false
  quantity: { name: Quantity, type: float, summarize: true }
  taxable: { name: Taxable, type: boolean }
  type: { name: "Item Type", type: string }
  unit_cost: { name: "Unit Cost", type: money, summarize: true }
  updated_at:
    name: Updated At
    type: datetime
    date_format: "Y-m-d H:i:s"
    writable: false
  company:
    name: Company
    type: join
    parent_column: tenant_id
    writable: false
    filterable: false
  customer:
    name: Customer
    type: join
    writable: false
  item:
    name: Item
    type: join
    parent_column: catalog_item_id
    join_column: internal_id
  metadata: { name: 'Metadata', type: metadata }
  subscription:
    name: Subscription
    type: join
    writable: false