fields:
  action:
    name: Action
    type: enum
    values:
      approve_bill: Approve Bill
      approve_vendor_credit: Approve Vendor Credit
      email: Email
      letter: Letter
      phone: Phone Call
      review: Review
  complete: { name: Complete, type: boolean }
  completed_date:
    name: "Completed Date"
    type: date
    writable: false
  created_at:
    name: Created At
    type: datetime
    date_format: "Y-m-d H:i:s"
    writable: false
  due_date: { name: "Due Date", type: date }
  id:
    name: ID
    type: string
    writable: false
  name: { name: Name, type: string }
  updated_at:
    name: Updated At
    type: datetime
    date_format: "Y-m-d H:i:s"
    writable: false
  company:
    name: Company
    type: join
    parent_column: tenant_id
    writable: false
    filterable: false
  customer: { name: Customer, type: join }
  member:
    name: Assignee
    type: join
    parent_column: user_id
    join_column: user_id