# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        orders.s3:
            adapter: aws
            options:
                client: aws.s3
                bucket: invoiced-orders
                prefix: '%app.api_log_env%/'
                options:
                    streamReads: true
