vich_uploader:
    db_driver: orm
    storage:   flysystem

    mappings:
        orders:
            upload_destination: orders.s3
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: true