aws:
  version: latest
  CloudWatch:
    region: us-west-2
  CloudWatchLogs:
    region: us-west-2
  DynamoDb:
    region: us-west-2
  S3:
    region: us-east-2
  Ses:
    region: us-west-2
  # Credentials are provided by the instance IAM role or env variables
  credentials: '@Aws\PsrCacheAdapter'