parameters:
  app.adyen_client_key: live_GBHVYX2ZKVCGXJWDKNMDUBHSQ4DVHJMD
  app.adyen_live_mode: true
  app.adyen_theme_id: ONBT42C2T22322695M3ZJQ6DGG54PJ
  app.api_domain: api.invoiced.com
  app.api_url: https://api.invoiced.com
  app.custom_domain_url: custom.invoiced.com
  app.dashboard_url: https://app.invoiced.com
  app.default_search_backend: elasticsearch
  app.domain: invoiced.com
  app.gocardless_environment: live
  app.inbound_email_domain: invoicedmail.com
  app.opp_client_url: 'https://private.onplanprocessing.com'
  app.opp_url: 'https://private.onplanprocessing.com:8443'
  app.opp_ui_url: 'https://onplanprocessing.com'
  app.port: 443
  app.protocol: https
  app.robots_default: index,follow
  app.s3_bucket_adyen_reports: invoiced-adyen-reports-live
  app.s3_bucket_documents: invoiced-documents
  app.s3_bucket_events: invoiced-events
  app.s3_bucket_region: us-east-2
  app.s3_bucket_webhooks: invoiced-webhooks
  app.textract_sns_role: arn:aws:iam::224792504733:role/Invoiced-Textract-Publisher-Role
  app.textract_sns_topic: arn:aws:sns:us-east-2:224792504733:AmazonTextract-Invoiced-Production-Invoice-Capture-SNS
  app.tokenization_url: https://tknz.invoiced.com
  app.files_url: https://files.invoiced.com
  asset.request_context.secure: true
  router.request_context.host: 'invoiced.com'
  router.request_context.scheme: 'https'
