parameters:
  app.adyen_client_key: test_Q67NQ6YFWND3XMZVB2D5CDUVUYM34G6J
  app.adyen_theme_id: ONBT42CLN22322695M2HPTT4M34FQX
  app.api_domain: api.sandbox.invoiced.com
  app.api_url: https://api.sandbox.invoiced.com
  app.avalara_environment: sandbox
  app.cache_namespace: invoicedsandbox
  app.csadmin_url: https://corp.sandbox.invoicedhq.com
  app.custom_domain_url: custom.sandbox.invoiced.com
  app.dashboard_url: https://app.sandbox.invoiced.com
  app.default_from_name: Invoiced Sandbox
  app.default_search_backend: elasticsearch
  app.domain: sandbox.invoiced.com
  app.flywire_checkout_url: https://checkout-api.demo.flywire.com/rest/payor/charge
  app.flywire_doc_verify_url: https://doc-verify.demo.flywire.com/api
  app.flywire_private_api_url: https://api.demo.flywire.com
  app.gocardless_environment: sandbox
  app.inbound_email_domain: sandbox.invoicedmail.com
  app.invoiced_sandbox: true
  app.invoiced_tokenization_url: https://tokenization.sandbox.invoiced.com
  app.opp_client_url: 'https://test.onplanprocessing.com'
  app.opp_url: 'https://test.onplanprocessing.com:8443'
  app.opp_ui_url: 'https://test.onplanprocessing.com'
  app.plaid_sandbox: true
  app.port: 443
  app.protocol: https
  app.quickbooks_userinfo_url: https://sandbox-accounts.platform.intuit.com/v1/openid_connect/userinfo
  app.s3_bucket_attachments: invoiced-attachments-sandbox
  app.s3_bucket_checks: invoiced-attachments-sandbox
  app.s3_bucket_document_pdfs: invoiced-attachments-sandbox
  app.s3_bucket_emails: invoiced-email-bodies-sandbox
  app.s3_bucket_exports: invoiced-exports-2-sandbox
  app.s3_bucket_imports: invoiced-imports-2-sandbox
  app.s3_bucket_qwc: invoiced-qwc-sandbox
  app.s3_bucket_reports: invoiced-reports-sandbox
  app.s3_textract_upload: invoiced-attachments-sandbox
  app.s3_bucket_adyen_reports: invoiced-adyen-reports-test
  app.s3_bucket_documents: invoiced-documents-sandbox
  app.s3_bucket_events: invoiced-events-sandbox
  app.s3_bucket_region: us-west-1
  app.s3_bucket_webhooks: invoiced-webhooks-sandbox
  app.textract_sns_role: arn:aws:iam::930714431012:role/Invoiced-Textract-Publisher-Role
  app.textract_sns_topic: arn:aws:sns:us-east-2:930714431012:AmazonTextract-Invoiced-Sandbox-Invoice-Capture-SNS
  app.title: Invoiced (Sandbox)
  app.files_url: https://files.sandbox.invoiced.com
  asset.request_context.secure: true
  router.request_context.host: 'sandbox.invoiced.com'
  router.request_context.scheme: 'https'
