name: CI

on:
  push:
    branches:
      - dev
  pull_request: {}

jobs:
  jshint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: |
          npm install -g jshint

      - name: JSHint
        run: |
          jshint assets/js/

  phpstan:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: gd,mailparse,mbstring,redis
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
            bin/.phpunit
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-interaction
          bin/phpunit install

      - name: Validate Composer
        run: |
          composer validate

      - name: Validate Symfony
        run: |
          bin/console lint:yaml  --parse-tags config
          bin/console lint:container
          bin/console lint:xliff translations
          bin/console lint:twig templates

      - name: PHPStan
        run: |
          vendor/bin/phpstan analyse --memory-limit=-1 --no-progress

  phpunit:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      APP_ENV: test
      REDIS_HOST: localhost
      RESQUE_HOST: localhost:6379
      TEST_ATTACHMENT_ENDPOINT: http://localhost:7000/
      TEST_DATABASE_URL: mysql://root:@127.0.0.1:3307/InvoicedTest

    steps:
      - uses: actions/checkout@v2

      - name: Start databases
        run:
          docker compose up -d database cache

      - name: Setup wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install xfonts-base xfonts-75dpi ghostscript
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
          sudo apt install ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb
          rm wkhtmltox_0.12.6.1-2.jammy_amd64.deb
          wkhtmltopdf --version

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: gd,mailparse,mbstring,redis
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
            bin/.phpunit
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-interaction --no-scripts
          bin/phpunit install

      - name: Configure application
        run: |
          mysql -uroot -h 127.0.0.1 -P 3307 -e "CREATE DATABASE InvoicedTest;"
          bin/console db:migrate
          bin/console config:build
          php -S 127.0.0.1:7000 -t public/ > /dev/null & # Start development server for custom PDF attachment tests

      - name: PHPUnit
        run: |
          bin/phpunit

  security-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Check for vulnerable dependencies
        uses: symfonycorp/security-checker-action@v3