name: Deploy

on:
  push:
    branches:
      - production
      - sandbox
      - dev

jobs:
  container:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      GITHUB_JOB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      REPO_NAME: ${{ github.event.repository.name }}
      SENTRY_WEBHOOK: ${{ secrets.SENTRY_WEBHOOK }}

    steps:
      - name: Determine environment
        uses: iamtheyammer/branch-env-vars@v1.1.2
        with:
          bevActionOnNoRef: error
          APP_ENV: |
            production:production
            sandbox:sandbox
            dev:staging
          AWS_REGION: |
            production:us-east-2
            sandbox:us-west-1
            dev:us-west-2
          ECS_CLUSTER: |
            production:InvoicedProduction
            sandbox:InvoicedSandbox
            dev:InvoicedStaging            
          REDIS_HOST: |
            production:production.renonf.ng.0001.use2.cache.amazonaws.com:6379
            sandbox:sandbox-2.kt5fq8.ng.0001.usw1.cache.amazonaws.com:6379
            dev:invoiced-staging-2.r0fyva.0001.usw2.cache.amazonaws.com:6379

      - uses: actions/checkout@v2

      - name: Start deploy notification
        run: .github/deploy/start.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache node dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          composer install --no-dev --no-interaction --optimize-autoloader --no-progress --no-scripts --ignore-platform-req=ext-redis --ignore-platform-req=ext-mailparse
          composer dump-autoload --optimize --no-dev --classmap-authoritative
          composer dump-env ${{ env.APP_ENV }} --empty
          npm install
          npm install -g grunt-cli

      - name: Compile assets
        run: |
          bin/console config:build
          grunt release
          rm -rf .env .env.local tests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push invoiced-nginx container
        uses: docker/build-push-action@v2.6.1
        with:
          file: docker/nginx/Dockerfile
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/invoiced-nginx:${{ env.APP_ENV }}
          cache-from: type=gha,scope=invoiced-nginx
          cache-to: type=gha,scope=invoiced-nginx,mode=max

      - name: Build and push invoiced container
        uses: docker/build-push-action@v2.6.1
        with:
          file: docker/php/Dockerfile
          context: .
          build-args: |
            PHP_ENVIRONMENT=production
            REDIS_HOST=${{ env.REDIS_HOST }}
            APP_ENV=${{ env.APP_ENV }}
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/invoiced:${{ env.APP_ENV }}
          cache-from: type=gha,scope=invoiced
          cache-to: type=gha,scope=invoiced,mode=max

      - name: Make ECS http task definition JSON
        run: |
          bin/console deploy:ecs-task-definition http ${{ env.APP_ENV }} > task-definition.http.json

      - name: Deploy ECS HTTP service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.http.json
          service: Invoiced
          cluster: ${{ env.ECS_CLUSTER }}

      - name: Make ECS resque-scheduler task definition JSON
        run: |
          bin/console deploy:ecs-task-definition resque-scheduler ${{ env.APP_ENV }} > task-definition.resque-scheduler.json

      - name: Deploy ECS Resque Scheduler service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.resque-scheduler.json
          service: InvoicedResqueScheduler
          cluster: ${{ env.ECS_CLUSTER }}

      - name: Make ECS resque-worker task definition JSON
        run: |
          bin/console deploy:ecs-task-definition resque-worker ${{ env.APP_ENV }} > task-definition.resque-worker.json

      - name: Deploy ECS Resque Worker service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.resque-worker.json
          service: InvoicedResqueWorker
          cluster: ${{ env.ECS_CLUSTER }}

      - name: Make ECS resque-batch-worker task definition JSON
        run: |
          bin/console deploy:ecs-task-definition resque-batch-worker ${{ env.APP_ENV }} > task-definition.resque-batch-worker.json

      - name: Deploy ECS Resque Batch Worker service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.resque-batch-worker.json
          service: InvoicedResqueBatchWorker
          cluster: ${{ env.ECS_CLUSTER }}

      - name: Make ECS console task definition JSON
        run: |
          bin/console deploy:ecs-task-definition console ${{ env.APP_ENV }} > task-definition.console.json

      - name: Deploy ECS console task
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        id: ecs-console
        with:
          task-definition: task-definition.console.json

      - name: Database migrations
        run: |
          NETWORK_CONFIG=$(<ecs/console/network-configuration.${{ env.APP_ENV }}.json)
          MIGRATE_COMMAND=$(<ecs/console/migrate-command.json)
          TASK_ARN=`aws ecs run-task \
            --cluster ${{ env.ECS_CLUSTER }} \
            --task-definition ${{ steps.ecs-console.outputs.task-definition-arn }} \
            --launch-type FARGATE \
            --network-configuration "$NETWORK_CONFIG" \
            --overrides "$MIGRATE_COMMAND" | jq -r '.tasks[0].taskArn' | sed 's~.*task/${{ env.ECS_CLUSTER }}/~~'`
          echo "Watch progress in the Amazon ECS console: https://${{ env.AWS_REGION }}.console.aws.amazon.com/ecs/v2/clusters/${{ env.ECS_CLUSTER }}/tasks/$TASK_ARN/logs"

      - name: Install cron jobs
        run: |
          CRON_JOBS=$(<ecs/cron/cron-jobs.${{ env.APP_ENV }}.json)
          aws events put-rule \
            --schedule-expression "cron(* * * * ? *)" --name InvoicedCron
          aws events put-targets \
            --rule "InvoicedCron" \
            --targets "$CRON_JOBS"

      - name: Successful deploy notification
        run: .github/deploy/succeeded.sh

      - name: Failed Notification
        run: .github/deploy/failed.sh
        if: ${{ failure() }} # Pick up events if the job fails.
