version: "3.9"

services:
  web:
    image: nginx:stable-alpine
    ports:
      - "1237:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params
    links:
      - php-fpm:localhost

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        PHP_ENVIRONMENT: development
    volumes:
      - .:/var/www/html

  database:
    image: mariadb:10.6
    ports:
      - "3308:3306"
    volumes:
      - csadmin_db:/var/lib/mysql
      - ./docker/mariadb:/etc/mysql/conf.d
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: CSAdmin

volumes:
  csadmin_db: