doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%app.database_url%'
                server_version: 10.5.8-MariaDB

            reporting:
                url: '%app.database_url%'
                server_version: 10.5.8-MariaDB

    orm:
        auto_generate_proxy_classes: false # disabled until we use Doctrine ORM
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false # disabled until we use Doctrine ORM
        mappings: ~ # disabled until we use Doctrine ORM
#            App:
#                is_bundle: false
#                type: attribute
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App
