twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        dashboardUrl: '%app.dashboard_url%'
        robotsDefault: '%app.robots_default%'
    paths:
        '%kernel.project_dir%/assets/styles': styles
    form_themes: ['bootstrap_5_layout.html.twig']