version: "3.9"

services:
  web:
    build:
      context: .
      args:
        API_URL: http:\/\/host.docker.internal:1234\/
        API_HOST: api.invoiced.localhost
    ports:
      - "1236:80"
    volumes:
      - ./build:/var/www/html
